### PR TITLE
Updates Comments

### PR DESCRIPTION
**Pull request by ngzax**
Updates files with comments so that they match the current state Also formats them consistently across all the files that contain the comments and adds matching comments to files that are missing them.

### CODE REVIEW

**Comment by xykj61** [comment]
Good work. Somehow this weird comment convention got started of putting file paths backward. I'm not sure if that was a part of the old system or something before I found Urbit, but nonetheless, it'd be super great if you could lastly normalize the comment paths so that they're full clay paths. Could you do this? A full clay path would be something like:

```
::  /===/app/foo/hoon
```

where `/===/` will default to the current ship/`@p`, the current desk and the current time (a full clay path, or `++beam`, is `/ship/desk/case/path`.

This is compared to the current:

```
::  /hoon/foo/app
```
Which has no good reason to still be here.

Then, this will be good for merge, and I'll deploy these promptly!

**Comment by ngzax** [comment]
Sure thing, will do.

**Comment by ngzax** [comment]
Paths are updated. I did not exhaustively go through all the files so there are some in there still using the old "reverse" path style. They are mostly files from taskk and tumblr. I thought maybe best to leave those. Let me know if you'd like me to hit those too.

**Comment by xykj61** [comment]
Awesome. I went through and improved most of the rest of the files. This should be good for now. Thanks @ngzax!

**Pull request merged**
