### PR TITLE
Added caesar.hoon

### PR DESCRIPTION
**Pull request by SMCassidy**
~dilbyn_tomtyd cleaned up this Caesar cipher generator and recommended I put in a pull request.

### CODE REVIEW

**Comment by ohAitch** [comment]
Looping through the input `n` times seems weird, any reason not to just go with a wraparound add?

<details><summary>Compare to:</summary>

```
::  A Caesar cipher generator
::
::  Call from dojo with +caesar ["message" n]
::
::::
  ::
|=  [a=tape b=@]  ^+  a
?~  a  a
:_  $(a t.a)
?:  &((lth 'a' i.a) (lth i.a 'z'))
  =.  i.a  (add b i.a)
  ?:((lth i.a 'z') i.a (sub i.a 26))  :: 'z' - 'a' wraparound
?:  &((lth 'A' i.a) (lth i.a 'Z'))
  =.  i.a  (add b i.a)
  ?:((lth i.a 'Z') i.a (sub i.a 26))  :: 'Z' - 'A' wraparound
i.a
```

</details>

**Comment by SMCassidy** [comment]
I really wrote it just to get better at hoon and give an example generator for beginners. I'm sure yours works much better even if it is a little more dense and fiddly.

**Comment by joshuareagan** [comment]
I don't think @ohAitch 's version gives the right answer:

```
> +caesar ["Z" 3]
"Z"
```

I think you need some `lte` substitutions for `lth` and then it works.

**Comment by ohAitch** [comment]
Yup, sorry!
I was mostly pointing towards the nested loops, and refactored the range check without subsequently running the code to verify it still did the right thing.

**Comment by joshuareagan** [comment]
@SMCassidy , if you're having a little trouble following @ohAitch 's version, take a look at this one:

```
|=  [a=tape b=@]
^-  tape
%+  turn  a
|=  c=@t
^-  @t
?.  ?|  &((gte c 'A') (lte c 'Z'))
        &((gte c 'a') (lte c 'z'))
    ==
  c
=.  c  (add c b)
?:  ?|  &((gth c 'Z') (lth c 'a'))
        (gth c 'z')
    ==
  (sub c 26)
c
```

It's more like yours in that it uses `turn` rather than using list `i` and `t` wings.  But I made two main changes: (1) instead of defining the `inc` gate in another core and then calling it, I directly defined a gate in my call to `turn`; and (2) I used @ohAitch 's idea for wrap-around addition.  Wrap-around addition is better because it allows us to avoid looping `b` times.  Does this make sense?

**Comment by SMCassidy** [comment]
Yup, that makes total sense.

I will say the file began as me wanting to progress beyond writing simple gates and trying to find a problem where I could define a core and then call an arm from it, to give me a sense of writing larger more structured programs, so that's why it looks like that.

**Comment by joshuareagan** [comment]
Learning cores is a noble goal.  We definitely need more beginner-friendly examples that really make full use of them.

**Comment by joshuareagan** [comment]
My implementation of the Caesar cypher is broken as well.

```
> +caesar ["THE QUICK BROWN FOX JUMPED OVER THE LAZY DOG." 15]
"cWT FdXRZ QaDfC UDg YdBETS DeTa cWT APih SDV."
```

The problem is that I failed to account for wrap-around addition of capital letters into the lower-case letters!  @SMCassidy 's program gets this right, however.

**Comment by joshuareagan** [comment]
Here's a corrected version for my Caesar gate:

```
|=  [a=tape b=@]
^-  tape
%+  turn  a
|=  c=@t
^-  @t
=/  new-c  (add c b)
?:  &((gte c 'A') (lte c 'Z'))
  ?:((gth new-c 'Z') (sub new-c 26) new-c)
?:  &((gte c 'a') (lte c 'z'))
  ?:((gth new-c 'z') (sub new-c 26) new-c)
c
```

**Comment by baudtack** [comment]
Closing this as it's quite old. Open a new pr if you still would like this to be added after verifying it still works.

**Pull request closed without merging**
