### PR TITLE
Now that Curtis isn't here to object, clean talkbot.

### PR DESCRIPTION
**Pull request by eglaysher**

### CODE REVIEW

**Review by Fang- — APPROVED** [review]
LGTM

**Comment by galenwp** [comment]
What is sssoft.io?

**Comment by baudtack** [comment]
Someone's software business site it looks like... registered to Mark Staarink

**Comment by ohAitch** [comment]
Mods are asleep, post ponies!

**Comment by Fang-** [comment]
This talkbot source code makes for bad and outdated example code anyway, not sure why it's still in.

**Pull request merged**
